
export const actionTypes = {

    SET_BANNER: "SET_BANNER",
    FETCH_MOVIES_PAGINATION: "FETCH_MOVIES_PAGINATION",
    FETCH_MOVIES: "FETCH_MOVIES",
    FETCH_MOVIE: "FETCH_MOVIE",

    PLAY_MODAL: "PLAY_MODAL",

    LOGIN_USER: "LOGIN_USER",
    LOGOUT_USER: "LOGOUT_USER",
    REGISTER_USER: "REGISTER_USER",
    FETCH_USER_INFO: "FETCH_USER_INFO",

    FETCH_THEATER: "FETCH_THEATER",
    FETCH_MOVIE_SCHEDULE: "FETCH_MOVIE_SCHEDULE",

    GET_BOOKING_INFO: "GET_BOOKING_INFO",
    GET_BOOKING_TICKET_INFO: "GET_BOOKING_TICKET_INFO",
    BOOKING_SEAT: "BOOKING_SEAT",
    FINISH_BOOKING: "FINISH_BOOKING",
    OVER_10_SEATS: "OVER_10_SEATS",
    TIME_OUT: "TIME_OUT",
    MOBILE_SET_STEP: "MOBILE_SET_STEP",
    SET_CHECKED: "SET_CHECKED",

    FETCH_TICKET_REQUEST: "FETCH_TICKET_REQUEST",
    HIDE_TICKET_REQUEST: "HIDE_TICKET_REQUEST",

    FETCH_BOOKING_INFO_REQUEST: "FETCH_BOOKING_INFO_REQUEST",
    HIDE_BOOKING_INFO_REQUEST: "HIDE_BOOKING_INFO_REQUEST",

    CHANGE_TAB: "CHANGE_TAB",
    CHANGE_TAB_TYPE: "CHANGE_TAB_TYPE",

    LOADING_LAZY_MOUNT: "LOADING_LAZY_MOUNT",
    LOADING_LAZY_UNMOUNT: "LOADING_LAZY_UNMOUNT",

    FETCH_USER_REQUEST: "FETCH_USER_REQUEST",
    FETCH_ARRAY_MOVIE_REQUEST: "FETCH_ARRAY_MOVIE_REQUEST",
    FETCH_THEATER_REQUEST: "FETCH_THEATER_REQUEST",

    HIDE_USER_REQUEST: "HIDE_USER_REQUEST",
    HIDE_ARRAY_MOVIE_REQUEST: "HIDE_ARRAY_MOVIE_REQUEST",
    HIDE_THEATER_REQUEST: "HIDE_THEATER_REQUEST",

    SELECT_RAPCHIEU: "SELECT_RAPCHIEU",
    SELECT_NGAYXEM: "SELECT_NGAYXEM",
    SELECT_SUATCHIEU: "SELECT_SUATCHIEU",
}


